version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "payment-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o3ixkw96uyep"
s3_prefix = "payment-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
